"""Added link to connections table

Revision ID: 9b29a89257c4
Revises: 2a4705d26709
Create Date: 2024-09-21 15:49:04.252700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b29a89257c4'
down_revision: Union[str, None] = '2a4705d26709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('link', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'connections', ['link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connections', type_='unique')
    op.drop_column('connections', 'link')
    # ### end Alembic commands ###
