"""'subscription-last-payment-optional'

Revision ID: aadfa3c2f689
Revises: 61b6af9430a4
Create Date: 2024-09-19 19:00:08.785806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadfa3c2f689'
down_revision: Union[str, None] = '61b6af9430a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'last_payment',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'last_payment',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
